### ISSUE TITLE
Testing: On Mac/Safari

### ISSUE THREAD

**Issue by Sacret** [Sacret/githubify#40]
It would be nice to test website on Mac/Safari. Need to test such pages and functionality:
- homepage for logged in (logged out) user
- page of another user
- tags operations (add, edit, remove)
- repos filtering (by tag, by type, by language, by repo name)
- repos sorting (by title, by created date, by updated date, by stars count)

**Comment by RonakKhandelwal** [comment]
I'd like to test the application on Mac. I'll do the testing on safari and chrome as well if required

**Comment by Sacret** [comment]
@RonakKhandelwal thanks!

**Comment by RonakKhandelwal** [comment]
Just provide me the link and what all there is to be tested a detailed use case if possible.

**Comment by Sacret** [comment]
The link is https://githubify.me/ 

Use cases:
- homepage for logged out user is just a description of the site (with login button)
- homepage for logged in user is a list of his/her github repos + accoun description
- you can open page of another user by adding username (like https://githubify.me/torvalds for Linus page)
- you can add a new tag by typing its name in textfield `Type comma-separated tags` under the repo name
- you can edit tag by clicking on pencil icon on hovering of tag name (blue one)
- you can remove tag by clicking on cross icon on hovering of tag name (blue one)
- you can use filters for tag/type/language by clicking on them (blue for tags, green for languages, grey for types)
- you can filter repos by name by typing itsname in textfield with search icon
- you can sort repos by choosing sorting option on the select with text `Sort by`

Hope it helps. Feel free to create issues for all the bugs you'll find

**Comment by choyiny** [comment]
When I use Chrome on Mac to click on Login with Github, it will block the popup. I think it is better for the login page to be a modal view?
