### ISSUE TITLE
Bug: No spacing between tag and input

### ISSUE THREAD

**Issue by tamtamchik** [Sacret/githubify#7]
Need spacing between input and tags:

<img width="367" alt="2015-12-23 9 54 31" src="https://cloud.githubusercontent.com/assets/265510/11972291/3fb071ee-a95b-11e5-9f79-0e1fcba6f71d.png">

**Comment by Sacret** [comment]
@tamtamchik is it Safari? I can't reproduce this bug in Chrome or Firefox

**Comment by tamtamchik** [comment]
@Sacret yep.

+upd. Checked in chrome. Looks good. Just not clear how it works in Chrome - margin bottom for `repo-tag` is 0.

**Comment by Sacret** [comment]
Magic! >_<

**Comment by tamtamchik** [comment]
@Sacret fixed! Thanks!
